# Copyright 2026 beamtalk_watcher authors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "beamtalk_watcher"
version = "0.1.0"

[dependencies]
http = { git = "https://github.com/jamesc/beamtalk-http", branch = "main" }
